#!/usr/bin/with-contenv bash

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

# Mount CIFS Share if configured and if Protection Mode is active
if bashio::config.has_value 'networkdisks'; then
    MOREDISKS=$(bashio::config 'networkdisks')
    CIFS_USERNAME=$(bashio::config 'cifsusername')
    CIFS_PASSWORD=$(bashio::config 'cifspassword')
    if bashio::config.has_value 'cifsversion'; then
        CIFS_VERSION_ARG=",vers=$(bashio::config 'cifsversion')"
    fi
    bashio::log.info "Network Disks mounting.. ${MOREDISKS}" && \
    for disk in $MOREDISKS 
    do
        bashio::log.info "Mount ${disk}"
        mkdir -p /$disk && \
            mount -t cifs -o username=$CIFS_USERNAME,password=$CIFS_PASSWORD$CIFS_VERSION_ARG $disk /$disk && \
            bashio::log.info "Success!"   
    done || \
    bashio::log.warning "Unable to mount external drives probably due to an incorrect login/password!"
fi

cd /app/sonarr/bin || exit

exec \
	s6-setuidgid abc mono --debug Sonarr.exe \
	-nobrowser -data=/data/config
